services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  # Repositories - make them public for external access
  Tourze\AzureOAuth2ClientBundle\Repository\:
    resource: '../../Repository/'
    public: true

  # Services
  Tourze\AzureOAuth2ClientBundle\Service\:
    resource: '../../Service/'

  # Controllers
  Tourze\AzureOAuth2ClientBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']

  # Main service - make it public for external access
  Tourze\AzureOAuth2ClientBundle\Service\AzureOAuth2Service:
    public: true
